// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: flex/Lexico.flex

package compilador;
import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\5\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\11\17\1\20\1\21\1\22"+
    "\1\23\1\24\2\0\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\2\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\36\1\44\1\45\1\46\2\36\1\47"+
    "\3\36\1\50\1\0\1\51\1\0\1\36\1\0\1\52"+
    "\1\53\1\36\1\54\1\55\1\32\1\56\1\34\1\57"+
    "\2\36\1\60\1\36\1\61\1\62\1\63\1\36\1\64"+
    "\1\45\1\46\2\36\1\47\3\36\1\65\1\0\1\66"+
    "\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\1\1\12\2\13\1\1\1\14"+
    "\1\15\1\16\1\17\13\20\1\21\1\22\2\20\1\23"+
    "\1\24\1\0\1\25\1\26\1\0\1\27\1\0\1\30"+
    "\1\31\1\32\1\33\7\20\1\34\1\20\1\35\3\20"+
    "\1\0\1\36\6\20\1\37\6\20\1\40\1\0\10\20"+
    "\1\0\1\20\1\41\1\42\1\20\1\43\1\0\2\20"+
    "\1\0\1\20\1\44\1\0\1\45\1\46\1\0\1\20"+
    "\2\0\1\20\2\0\1\20\2\0\1\47\1\0\1\50"+
    "\1\0\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\67\0\156\0\67\0\245\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\334\0\67\0\u0113\0\u014a"+
    "\0\u0181\0\67\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb"+
    "\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\67\0\67\0\u04ba\0\u04f1\0\67\0\67\0\245\0\67"+
    "\0\334\0\u0113\0\67\0\u0528\0\67\0\67\0\67\0\67"+
    "\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b\0\u0672\0\u06a9\0\u02cb"+
    "\0\u06e0\0\u02cb\0\u0717\0\u074e\0\u0785\0\u07bc\0\u02cb\0\u07f3"+
    "\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906\0\u02cb\0\u093d\0\u0974"+
    "\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u02cb\0\u0a87\0\u0abe\0\u0af5"+
    "\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad"+
    "\0\u02cb\0\u02cb\0\u0ce4\0\u02cb\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0"+
    "\0\u0df7\0\u02cb\0\u0e2e\0\u02cb\0\u02cb\0\u0e65\0\u0e9c\0\u0ed3"+
    "\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u02cb"+
    "\0\u108b\0\67\0\u10c2\0\67";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\2\30\1\34\4\30\1\35\1\36\1\30"+
    "\1\37\1\30\1\40\1\41\1\42\1\26\1\43\1\30"+
    "\1\44\1\30\1\34\2\30\1\35\1\36\1\30\1\45"+
    "\1\46\71\0\1\3\64\0\2\47\2\0\1\47\1\50"+
    "\61\47\16\0\2\51\63\0\1\51\1\0\2\52\63\0"+
    "\1\51\1\0\2\20\72\0\1\53\60\0\1\54\5\0"+
    "\1\55\1\56\65\0\1\57\66\0\1\60\61\0\2\30"+
    "\5\0\14\30\1\61\6\30\2\0\7\30\1\61\3\30"+
    "\20\0\2\30\5\0\4\30\1\62\16\30\2\0\3\30"+
    "\1\63\7\30\20\0\2\30\5\0\23\30\2\0\13\30"+
    "\20\0\2\30\5\0\4\30\1\64\16\30\2\0\13\30"+
    "\20\0\2\30\5\0\12\30\1\65\1\30\1\66\6\30"+
    "\2\0\6\30\1\65\4\30\20\0\2\30\5\0\12\30"+
    "\1\67\10\30\2\0\6\30\1\67\4\30\20\0\2\30"+
    "\5\0\5\30\1\70\6\30\1\71\6\30\2\0\7\30"+
    "\1\71\3\30\20\0\2\30\5\0\17\30\1\72\3\30"+
    "\2\0\12\30\1\72\20\0\2\30\5\0\17\30\1\73"+
    "\3\30\2\0\12\30\1\73\20\0\2\30\5\0\21\30"+
    "\1\74\1\30\2\0\13\30\20\0\2\30\5\0\7\30"+
    "\1\75\13\30\2\0\13\30\20\0\2\30\5\0\4\30"+
    "\1\63\16\30\2\0\3\30\1\63\7\30\20\0\2\30"+
    "\5\0\12\30\1\65\10\30\2\0\6\30\1\65\4\30"+
    "\2\0\15\54\1\76\51\54\16\0\2\30\5\0\3\30"+
    "\1\77\17\30\2\0\2\30\1\77\10\30\20\0\2\30"+
    "\5\0\6\30\1\100\12\30\1\101\1\30\2\0\13\30"+
    "\20\0\2\30\5\0\21\30\1\101\1\30\2\0\13\30"+
    "\20\0\2\30\5\0\2\30\1\102\20\30\2\0\13\30"+
    "\20\0\2\30\5\0\20\30\1\103\2\30\2\0\13\30"+
    "\20\0\2\30\5\0\3\30\1\104\17\30\2\0\13\30"+
    "\20\0\2\30\5\0\15\30\1\105\5\30\2\0\10\30"+
    "\1\105\2\30\20\0\2\30\5\0\21\30\1\106\1\30"+
    "\2\0\13\30\20\0\2\30\5\0\10\30\1\107\12\30"+
    "\2\0\5\30\1\107\5\30\20\0\2\30\5\0\17\30"+
    "\1\110\3\30\2\0\12\30\1\110\20\0\2\30\5\0"+
    "\10\30\1\111\12\30\2\0\5\30\1\111\5\30\2\0"+
    "\15\54\1\76\6\54\1\3\42\54\16\0\2\30\5\0"+
    "\10\30\1\112\12\30\2\0\13\30\20\0\2\30\5\0"+
    "\22\30\1\113\2\0\13\30\20\0\2\30\5\0\12\30"+
    "\1\114\10\30\2\0\13\30\20\0\2\30\5\0\4\30"+
    "\1\115\16\30\2\0\3\30\1\115\7\30\16\0\1\116"+
    "\1\0\2\30\5\0\3\30\1\117\17\30\2\0\13\30"+
    "\20\0\2\30\5\0\1\120\22\30\2\0\1\120\12\30"+
    "\20\0\2\30\5\0\14\30\1\121\6\30\2\0\7\30"+
    "\1\121\3\30\20\0\2\30\5\0\10\30\1\122\12\30"+
    "\2\0\5\30\1\122\5\30\20\0\2\30\5\0\12\30"+
    "\1\123\10\30\2\0\6\30\1\123\4\30\20\0\2\30"+
    "\5\0\14\30\1\124\6\30\2\0\13\30\20\0\2\30"+
    "\5\0\4\30\1\125\16\30\2\0\3\30\1\125\7\30"+
    "\20\0\2\30\5\0\1\126\22\30\2\0\13\30\45\0"+
    "\1\127\41\0\2\30\5\0\4\30\1\130\16\30\2\0"+
    "\13\30\20\0\2\30\5\0\21\30\1\131\1\30\2\0"+
    "\13\30\20\0\2\30\5\0\21\30\1\132\1\30\2\0"+
    "\13\30\20\0\2\30\5\0\14\30\1\133\6\30\2\0"+
    "\7\30\1\133\3\30\20\0\2\30\5\0\4\30\1\134"+
    "\16\30\2\0\3\30\1\134\7\30\16\0\1\135\1\0"+
    "\2\30\5\0\23\30\2\0\13\30\20\0\2\30\5\0"+
    "\4\30\1\136\16\30\2\0\3\30\1\136\7\30\20\0"+
    "\2\30\5\0\17\30\1\137\3\30\2\0\13\30\46\0"+
    "\1\140\40\0\2\30\5\0\2\30\1\141\20\30\2\0"+
    "\13\30\20\0\2\30\5\0\6\30\1\142\14\30\2\0"+
    "\4\30\1\142\6\30\45\0\1\143\41\0\2\30\5\0"+
    "\14\30\1\144\6\30\2\0\7\30\1\144\3\30\20\0"+
    "\2\30\5\0\4\30\1\145\16\30\2\0\13\30\44\0"+
    "\1\146\42\0\2\30\5\0\12\30\1\147\10\30\2\0"+
    "\13\30\46\0\1\150\55\0\1\151\51\0\2\30\5\0"+
    "\1\152\22\30\2\0\13\30\44\0\1\153\70\0\1\154"+
    "\40\0\2\30\5\0\17\30\1\155\3\30\2\0\13\30"+
    "\35\0\1\156\60\0\1\157\57\0\2\30\5\0\4\30"+
    "\1\160\16\30\2\0\13\30\46\0\1\161\62\0\1\162"+
    "\53\0\1\163\101\0\1\164\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4345];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\1\1\6\11\1\1\1\11"+
    "\3\1\1\11\16\1\2\11\2\1\2\11\1\0\1\11"+
    "\1\1\1\0\1\11\1\0\4\11\15\1\1\0\17\1"+
    "\1\0\10\1\1\0\5\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\1\1\2\0\1\1\2\0\1\1"+
    "\2\0\1\1\1\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  final int MAX_STRING = 100;
  final int MAX_INT = Short.MAX_VALUE;
  final float MAX_FLOAT = Float.MAX_VALUE;

  private Float verifyReal(String x) throws Exception {
      Float f = Float.parseFloat(x);
      if (f < -MAX_FLOAT || f > MAX_FLOAT) {
          throw new Exception("Real out of range");
      }
      return f;
  }
  private Integer verifyInt(String x) throws Exception {
      Integer i = Integer.parseInt(x);
      if (i < -MAX_INT || i > MAX_INT) {
          throw new Exception("Integer out of range");
      }
      return i;
  }
  private String verifyString(String x) throws Exception {
      x = x.substring(1, x.length()-1);
      if (x.length() > MAX_STRING) {
          throw new Exception("Maximum string length exceeded");
      }
      return x;
  }

  private Symbol symbol(int type) {
    return new JavaSymbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new JavaSymbol(type, yyline+1, yycolumn+1, value);
  }

  /**
   * Parecido a debug_next_token(), pero devuelve también la línea y la columna, la salida es más estética
   */
  public JavaSymbol debuguearProximoToken() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "Linea: " + (yyline+1) + ", Columna: " + (yycolumn+1) + ", Token: " + getTokenName(s.sym) + ", Lexema: "+ yytext());
    return new JavaSymbol(s.sym, yyline+1, yycolumn+1, s.left, s.right, s.value);
  }

  /**
   * Igual getTokenName(), pero la salida es más estética
   */
  public String getNombreToken(int token) {
    return getTokenName(token);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException("Illegal character \""+yytext()+"\" at line "+yyline+", column "+yycolumn);
            }
            // fall through
          case 42: break;
          case 2:
            { /**/
            }
            // fall through
          case 43: break;
          case 3:
            { return symbol(NOT);
            }
            // fall through
          case 44: break;
          case 4:
            { return symbol(LPAREN);
            }
            // fall through
          case 45: break;
          case 5:
            { return symbol(RPAREN);
            }
            // fall through
          case 46: break;
          case 6:
            { return symbol(MULT);
            }
            // fall through
          case 47: break;
          case 7:
            { return symbol(PLUS);
            }
            // fall through
          case 48: break;
          case 8:
            { return symbol(COMMA);
            }
            // fall through
          case 49: break;
          case 9:
            { return symbol(MINUS);
            }
            // fall through
          case 50: break;
          case 10:
            { return symbol(DIV);
            }
            // fall through
          case 51: break;
          case 11:
            { try {
                                      return symbol(INTEGER_LITERAL, verifyInt(yytext()));
                                    } catch (Exception e) {
                                      e.printStackTrace();
                                      return null;
                                    }
            }
            // fall through
          case 52: break;
          case 12:
            { return symbol(SEMICOLON);
            }
            // fall through
          case 53: break;
          case 13:
            { return symbol(LT, yytext());
            }
            // fall through
          case 54: break;
          case 14:
            { return symbol(ASSIGN);
            }
            // fall through
          case 55: break;
          case 15:
            { return symbol(GT, yytext());
            }
            // fall through
          case 56: break;
          case 16:
            { return symbol(IDENTIFIER, yytext());
            }
            // fall through
          case 57: break;
          case 17:
            { return symbol(LBRACK);
            }
            // fall through
          case 58: break;
          case 18:
            { return symbol(RBRACK);
            }
            // fall through
          case 59: break;
          case 19:
            { return symbol(LBRACE);
            }
            // fall through
          case 60: break;
          case 20:
            { return symbol(RBRACE);
            }
            // fall through
          case 61: break;
          case 21:
            { try {
                                      return symbol(STRING_LITERAL, verifyString(yytext()));
                                    } catch (Exception e) {
                                      e.printStackTrace();
                                      return null;
                                    }
            }
            // fall through
          case 62: break;
          case 22:
            { try {
                                      return symbol(FLOATING_POINT_LITERAL, verifyReal(yytext()));
                                    } catch (Exception e) {
                                      e.printStackTrace();
                                      return null;
                                    }
            }
            // fall through
          case 63: break;
          case 23:
            { return symbol(VARASSIGN);
            }
            // fall through
          case 64: break;
          case 24:
            { return symbol(LTEQ, yytext());
            }
            // fall through
          case 65: break;
          case 25:
            { return symbol(NOTEQ, yytext());
            }
            // fall through
          case 66: break;
          case 26:
            { return symbol(EQEQ, yytext());
            }
            // fall through
          case 67: break;
          case 27:
            { return symbol(GTEQ, yytext());
            }
            // fall through
          case 68: break;
          case 28:
            { return symbol(IF);
            }
            // fall through
          case 69: break;
          case 29:
            { return symbol(OR);
            }
            // fall through
          case 70: break;
          case 30:
            { return symbol(AND);
            }
            // fall through
          case 71: break;
          case 31:
            { return symbol(INT, yytext());
            }
            // fall through
          case 72: break;
          case 32:
            { return symbol(ELSE);
            }
            // fall through
          case 73: break;
          case 33:
            { return symbol(FLOAT, yytext());
            }
            // fall through
          case 74: break;
          case 34:
            { return symbol(PRINT);
            }
            // fall through
          case 75: break;
          case 35:
            { return symbol(WHILE);
            }
            // fall through
          case 76: break;
          case 36:
            { return symbol(STRING, yytext());
            }
            // fall through
          case 77: break;
          case 37:
            { return symbol(BETWEEN);
            }
            // fall through
          case 78: break;
          case 38:
            { return symbol(DECLARE);
            }
            // fall through
          case 79: break;
          case 39:
            { return symbol(ENDDECLARE);
            }
            // fall through
          case 80: break;
          case 40:
            { return symbol(ENDPROGRAM);
            }
            // fall through
          case 81: break;
          case 41:
            { return symbol(BEGINPROGRAM);
            }
            // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   */
  private static String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexico [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexico scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexico(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
