
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 16 14:46:19 ART 2023
//----------------------------------------------------

package compilador;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 37;
  public static final int GTEQ = 28;
  public static final int MULT = 35;
  public static final int LTEQ = 25;
  public static final int BEGINPROGRAM = 2;
  public static final int BETWEEN = 13;
  public static final int LPAREN = 14;
  public static final int INT = 6;
  public static final int MINUS = 34;
  public static final int RPAREN = 15;
  public static final int NOT = 30;
  public static final int SEMICOLON = 20;
  public static final int AND = 22;
  public static final int LT = 24;
  public static final int OR = 23;
  public static final int COMMA = 21;
  public static final int DIV = 36;
  public static final int VARASSIGN = 31;
  public static final int ENDPROGRAM = 3;
  public static final int PLUS = 33;
  public static final int ASSIGN = 32;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int ENDDECLARE = 5;
  public static final int error = 1;
  public static final int EQEQ = 26;
  public static final int DECLARE = 4;
  public static final int LBRACK = 18;
  public static final int FLOATING_POINT_LITERAL = 39;
  public static final int LBRACE = 16;
  public static final int ELSE = 11;
  public static final int RBRACK = 19;
  public static final int WHILE = 9;
  public static final int FLOAT = 7;
  public static final int RBRACE = 17;
  public static final int STRING = 8;
  public static final int GT = 29;
  public static final int PRINT = 12;
  public static final int NOTEQ = 27;
  public static final int IDENTIFIER = 40;
  public static final int INTEGER_LITERAL = 38;
}

